eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
      #是否使用IP定义注册中心的地址
      preferIpAddress: true
server:
  port: 9001
spring:
  application:
    name: cloud-client